### ISSUE TITLE
Change logical ID

### ISSUE THREAD

**Issue by paaacman** [lunarok/jeedom_espeasy#12]
Hello,  
First : thank for your plugin, it's nice and easy to use.  

If I understand the code, the origin IP address of the EspEasy device is used as a logical id.
https://github.com/lunarok/jeedom_espeasy/blob/3ed606fb55cc8a4f6910235a67c0ad915e0c4455/core/api/jeeEspeasy.php#L31

Is it possible to use the device name `$device`, or a slug of the device as the logical ID ?

I use Jeedom on Docker, so very EspEasy device call is from the same IP address, so it results in only 1 device in Jeedom with commands of alls my devices.  

Someone beind a proxy should have the same problem.

Bye,

Paaacman

**Comment by lunarok** [comment]
Hi,

A device name can be changed, it will destroy the link. IP are to be set on
the DHCP as static.
On reverse, can be done by the reverse to pass the IP transfered (or you
are blind of whatever comes to your jeedom)
Not just ESPeasy will be affected but many other plugins use the IP as
criteria for ID

**Comment by paaacman** [comment]
Hello,

Thanks for your answer.

With a Docker network in "bridge" mode I cannot get the client original IP, so I cannot use it in the reverse proxy (it was a good idea, I didn't though about it).
I tried try to put Docker network in "host" mode to be directly connected to the host network, and change the default Apache and SSHD port, but it's not working yet.

I close the issue if we don't have a solution involving your plugin.

Thank again for your work.
