### ISSUE TITLE
Installation des dépendances en échec

### ISSUE THREAD

**Issue by wixaw** [lunarok/jeedom_espeasy#13]
Bonjour @lunarok 

A l'installation des dépendances sur jeedom, le status est NOK et j'obtiens ceci dans les logs systeme 

```
PWD=/var/www/html/plugins/espeasy/resources ; USER=root ; COMMAND=/usr/bin/apt-get -y install lsb-release
PWD=/var/www/html/plugins/espeasy/resources ; USER=root ; COMMAND=/bin/rm -rf node_modules
PWD=/var/www/html/plugins/espeasy/resources ; USER=root ; COMMAND=/bin/chown -R www-data node_modules

```

Je ne sais pas comment est écrit le post install, j'aurais aimé pouvoir le modifier pour supprimer le rm ou le chown

Merci
William

**Comment by Belugha** [comment]
Bonjour @lunarok 

Même pb, en fait cela est du à la version de Debian 9 qui est toujours en 32 bits.
NodeJS n'est plus compatible, y-a-t-il un moyen de laisser l'ancienne version de NodeJS ou de modifier le fichier de config ?
Merci
