### ISSUE TITLE
Probleme GenericHTTP & Url Encode 

### ISSUE THREAD

**Issue by jujuinparis** [lunarok/jeedom_espeasy#14]
Bonjour

Il semblerait que la dernière version de EspEasy ajoute un encoding supplémentaire sur les requetes envoyées au controller Generic Http.

voila ce que ca donne

Ancien firmware 👍
We've got a request for /device=SonoffPow&taskid=0&cmd=Current%20%28A%29&value=1.82 from XXXXXXX
Calling Jeedom http://127.0.0.1:8088/plugins/espeasy/core/api/jeeEspeasy.php?apikey=XXXXXX&device=SonoffPow&taskid=0&cmd=Current%20%28A%29&value=1.82&ip=XXXXX

Nouveau firmware 20191208

We've got a request for /%2fdevice%3dTouchInterCharline%26taskid%3d0%26cmd%3dweb%26value%3d2578 from XXXXX

et donc exceptions en pagailles coé jeedom

Mon fix 👍 

Dans Espeasy.js

function answer(req, res) {
    var ipString = req.connection.remoteAddress;
    var decodeUrl = decodeURIComponent(req.url).replace(/[\/]/g,"");
    console.log("We have got a request for " + decodeUrl + " from " + ipString);
    urlj = urlJeedom + "&" + decodeUrl+ "&ip=" + ipString;

ca fonctionne à nouveau :)

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_espeasy/commit/0c40d3cf909bdb7dd297020e65cb5fbc433be4cc
