### ISSUE TITLE
Action Info liée : select non peuplé initialement

### ISSUE THREAD

**Issue by Bbillyben** [lunarok/jeedom_espeasy#18]
Bonjour Lunarok,

jeedom v4.1.22
espeasy v2020-07-30 01:00:29

J'ai noté récemment, quand j'ouvre un équipement espeasy, pour une commande 'action', la liste des commande info disponible à liée n'est pas remplie. si je rafraichi la page en restant sur l'équipement, celle-ci se peuple.

Ce qui à pour effet de mettre toutes les configuration des commande info liée dans les commande action à 'aucun' si on ne fait pas la manip de reload la page.

Je n'ai pas constaté ce comportement avant la mise à jour en 4.1.22, mais je n'avais pas ajouter d'équipement espeasy depuis un bail.

en prenant exemple sur le plugin virtuel, dans `/plugins/espeasy/desktop/js/espeasy.js`, 

si je remplace ligne 254

`id: $(".li_eqLogic.active").attr('data-eqLogic_id'),`

par

`id:  $('.eqLogicAttr[data-l1key=id]').value(),`

je retrouve le comportement attendu.

a ta dispo pour plus d'info. 

Je n'ai pas PR car je n'ai aucune idée de l'impact sur d'autre version de jeedom...

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_espeasy/commit/14d35810412920ed443106a3fcea9c7f888d6c74
