### ISSUE TITLE
Ajout d'un champ de sélection "valeur de la commande" sur les actions

### ISSUE THREAD

**Issue by BadWolf42** [lunarok/jeedom_espeasy#4]
Afin de pouvoir utiliser les widgets, il me semble qu'il est nécessaire de sélectionner une "valeur de la commande". Serait-il possible d'ajouter un menu déroulant, comme ici pour "Etat" dans un virtuel :
![image](https://user-images.githubusercontent.com/8396512/35611063-0bf8edc8-0664-11e8-991c-6fac1f4df9b0.png)
Merci

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_espeasy/commit/51b8d773190995247c63ae49dae0e42c21a7f426
