### ISSUE TITLE
lien vers images tous cassés

### ISSUE THREAD

**Issue by Kurairaito** [lunarok/jeedom_espeasy#6]
Bonjour,

Lors d'une nouvelle installation, le dossier doc (sans le "s") n'existe pas et les liens vers les images sont tous cassé.

exemple : création d'une jauge, l'image pointe vers "plugins/espeasy/doc/images/node_jauge.png", mais le fichier n'existe pas.

deuxième exemple : après la sauvegarde de la jauge, sur la page qui liste tout les espeasy, l'image pointe vers "plugins/espeasy/doc/images/espeasy_icon.png", mais ce fichier se trouve en fait dans le dossier "plugins/espeasy/plugin_info/espeasy_icon.png"

version stable 2018-03-29 06:46:43

Il semblerait que les utilisateurs ayant migré d'une ancienne version ne soient pas affectés car le dossier n'a pas été supprimé lors des mises à jour. 

Cordialement,
Kurairaito

**Comment by Jean-Mercier** [comment]
#7 Merge request done to fix it

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_espeasy/commit/3ed606fb55cc8a4f6910235a67c0ad915e0c4455

**Comment by Gis70** [comment]
salut, peux tu vérifier tous les liens dans le fichier espeasy.php car ta solution ne fonctionne pas à 100%,en effet l'icone par défaut est affiché partout, mais pas les icônes spécifiques. Cdlt.
